# Generated by Django 5.2.5 on 2025-08-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='referral_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
